version: 0.2

phases:
  # install:
  #   commands:
  #     - wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
  #     - sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
  build:
    commands:      
      - echo Build started on `date`
      - echo $BRANCH
      - cd cdk && npm install && npm run build && npm run cdk -- deploy --require-approval never
      - echo Build completed on `date`
