version: '3.9'

services:
  db:
    image: postgres:13
    container_name: linendev_postgres
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - APP_DB=linendev,linentest
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./postgres/initdb:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: linendev_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
