# Common build stage
FROM public.ecr.aws/docker/library/node:16 AS common-build-stage
COPY . ./app
WORKDIR /app
RUN yarn install
EXPOSE 3000


# Production build stage
FROM common-build-stage as production-build-stage
ENV NODE_ENV production
RUN yarn build
RUN cd /app/apps/web && yarn build:api