AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApiSyncUri:
    Type: String
    Default: linen.ngrok.io
    Description: Enter our ELB/Fargate Uri without https:// prefix
Resources:
  SyncTriggerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/lambda/DiscordSync-Poc-SyncTrigger'
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName:
            Fn::Join:
              - '-'
              - - DiscordSync
                - Poc
                - lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/DiscordSync-Poc*:*
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/DiscordSync-Poc*:*:*
      Path: '/'
      RoleName:
        Fn::Join:
          - '-'
          - - DiscordSync
            - Poc
            - Ref: AWS::Region
            - lambdaRole
  SyncTriggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          const https = require('https');
          module.exports.handler = async () => {
            return await new Promise((res, rej) => {
              https.get(`https://${process.env.SYNC_URL}/api/scripts/discordSyncJob`, (resp) => {
                let data = '';
                resp.on('data', (chunk) => {
                  data += chunk;
                });
                resp.on('end', () => {
                  console.log(data);
                  res(data)
                });
              }).on("error", (err) => {
                console.log("Error: " + err.message);
                rej(err)
              });
            })
          };
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: DiscordSync-Poc-SyncTrigger
      MemorySize: 256
      Environment:
        Variables:
          SYNC_URL:
            Ref: ApiSyncUri
      Timeout: 30
      Role:
        Fn::GetAtt:
          - IamRoleLambdaExecution
          - Arn
    DependsOn:
      - SyncTriggerLogGroup
  DiscordSyncPocSyncTriggerRule1EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: DiscordSync-Poc-SyncTrigger-rule-1
      ScheduleExpression: cron(0 0 * * ? *) # every 0:00h of GMT-0
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - SyncTriggerLambdaFunction
              - Arn
          Id: DiscordSync-Poc-SyncTrigger-rule-1-target
  SyncTriggerEventBridgeLambdaPermission1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: SyncTriggerLambdaFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::Join:
          - ':'
          - - arn
            - Ref: AWS::Partition
            - events
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - Fn::Join:
                - '/'
                - - rule
                  - DiscordSync-Poc-SyncTrigger-rule-1
