import Link from 'next/link';
import React from 'react';
export default function Privacy() {
  return (
    <div className="relative py-16">
      <div className="lg:block lg:absolute lg:inset-y-0 lg:h-full lg:w-full">
        <div className="relative h-full text-lg max-w-prose mx-auto space-y-4">
          <Link
            className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-600"
            href="/"
            passHref
          >
            Back to Home
          </Link>
          <h3 id="privacy-notice">PRIVACY NOTICE</h3>
          <div>Effective date: 08/31/2022</div>

          <div>Introduction</div>

          <div>Welcome to Rebase Corporation</div>

          <div>
            Rebase Corporation (“us”, “we”, or “our”) operates Linen.dev
            (hereinafter referred to as “Service”).
          </div>

          <div>
            Our Privacy Policy governs your visit to Linen.dev, and explains how
            we collect, safeguard and disclose information that results from
            your use of our Service.
          </div>

          <div>
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions.
          </div>

          <div>
            Our Terms and Conditions (“Terms”) govern all use of our Service and
            together with the Privacy Policy constitutes your agreement with us
            (“agreement”).
          </div>

          <div>Definitions</div>

          <div>
            SERVICE means the Linen.dev website operated by Rebase Corporation
          </div>

          <div>
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </div>
          <div>
            USAGE DATA is data collected automatically either generated by the
            use of Service or from Service infrastructure itself (for example,
            the duration of a page visit).
          </div>
          <div>
            COOKIES are small files stored on your device (computer or mobile
            device).
          </div>
          <div>
            DATA CONTROLLER means a natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data.
          </div>
          <div>
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
          </div>
          <div>
            DATA SUBJECT is any living individual who is the subject of Personal
            Data.
          </div>
          <div>
            THE USER is the individual using our Service. The User corresponds
            to the Data Subject, who is the subject of Personal Data.
          </div>
          <div>Information Collection and Use</div>
          <div>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </div>
          <div>Types of Data Collected</div>
          <div>Personal Data</div>
          <div>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:
          </div>
          <div>Email address</div>
          <div>First name and last name</div>
          <div>Cookies and Usage Data</div>
          <div>
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or by
            emailing at help@linen.dev.
          </div>
          <div>Usage Data</div>
          <div>
            We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through a mobile
            device (“Usage Data”).
          </div>
          <div>
            This Usage Data may include information such as your computer&apos;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </div>
          <div>
            When you access Service with a mobile device, this Usage Data may
            include information such as the type of mobile device you use, your
            mobile device unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
          </div>
          <div>Tracking Cookies Data</div>
          <div>
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </div>
          <div>
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our Service.
          </div>
          <div>
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </div>
          <div>Examples of Cookies we use:</div>
          <div>
            Session Cookies: We use Session Cookies to operate our Service.
          </div>
          <div>
            Preference Cookies: We use Preference Cookies to remember your
            preferences and various settings.
          </div>
          <div>
            Security Cookies: We use Security Cookies for security purposes.
          </div>
          <div>
            Advertising Cookies: Advertising Cookies are used to serve you with
            advertisements that may be relevant to you and your interests.
          </div>
          <div>Use of Data</div>
          <div>
            Rebase Corporation uses the collected data for various purposes:
          </div>
          <div>to provide and maintain our Service;</div>
          <div>to notify you about changes to our Service;</div>
          <div>
            to allow you to participate in interactive features of our Service
            when you choose to do so;
          </div>
          <div>to provide customer support;</div>
          <div>
            to gather analysis or valuable information so that we can improve
            our Service;
          </div>
          <div>to monitor the usage of our Service;</div>
          <div>to detect, prevent and address technical issues;</div>
          <div>to fulfill any other purpose for which you provide it;</div>
          <div>
            to carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection;
          </div>
          <div>
            to provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.;
          </div>
          <div>
            to provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </div>
          <div>
            in any other way we may describe when you provide the information;
          </div>
          <div>for any other purpose with your consent.</div>
          <div>Retention of Data</div>
          <div>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </div>
          <div>
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this
            data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </div>
          <div>Transfer of Data</div>
          <div>
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </div>
          <div>
            If you are located outside United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to United States and process it there.
          </div>
          <div>
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </div>
          <div>
            Rebase Corporation will take all the steps reasonably necessary to
            ensure that your data is treated securely and in accordance with
            this Privacy Policy and no transfer of your Personal Data will take
            place to an organisation or a country unless there are adequate
            controls in place including the security of your data and other
            personal information.
          </div>
          <div>Disclosure of Data</div>
          <div>
            We may disclose personal information that we collect, or you
            provide:
          </div>
          <div>
            Disclosure for Law Enforcement. Under certain circumstances, we may
            be required to disclose your Personal Data if required to do so by
            law or in response to valid requests by public authorities.
          </div>
          <div>
            Business Transaction. If we or our subsidiaries are involved in a
            merger, acquisition or asset sale, your Personal Data may be
            transferred.
          </div>
          <div>Other cases. We may disclose your information also:</div>
          <div>to our subsidiaries and affiliates;</div>
          <div>
            to contractors, service providers, and other third parties we use to
            support our business;
          </div>
          <div>Security of Data</div>
          <div>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </div>
          <div>
            Your Data Protection Rights Under General Data Protection Regulation
            (GDPR)
          </div>
          <div>
            If you are a resident of the European Union (EU) and European
            Economic Area (EEA), you have certain data protection rights,
            covered by GDPR. – See more at
            https://eur-lex.europa.eu/eli/reg/2016/679/oj
          </div>
          <div>
            We aim to take reasonable steps to allow you to correct, amend,
            delete, or limit the use of your Personal Data.
          </div>
          <div>
            If you wish to be informed what Personal Data we hold about you and
            if you want it to be removed from our systems, please email us at
            help@linen.dev.
          </div>
          <div>
            In certain circumstances, you have the following data protection
            rights:
          </div>
          <div>
            the right to access, update or to delete the information we have on
            you;
          </div>
          <div>
            the right of rectification. You have the right to have your
            information rectified if that information is inaccurate or
            incomplete;
          </div>
          <div>
            the right to object. You have the right to object to our processing
            of your Personal Data;
          </div>
          <div>
            the right of restriction. You have the right to request that we
            restrict the processing of your personal information;
          </div>
          <div>
            the right to data portability. You have the right to be provided
            with a copy of your Personal Data in a structured, machine-readable
            and commonly used format;
          </div>
          <div>
            the right to withdraw consent. You also have the right to withdraw
            your consent at any time where we rely on your consent to process
            your personal information;
          </div>
          <div>
            Please note that we may ask you to verify your identity before
            responding to such requests. Please note, we may not able to provide
            Service without some necessary data.
          </div>
          <div>
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </div>
          <div>
            Your Data Protection Rights under the California Privacy Protection
            Act (CalOPPA)
          </div>
          <div>
            CalOPPA is the first state law in the nation to require commercial
            websites and online services to post a privacy policy. The law’s
            reach stretches well beyond California to require a person or
            company in the United States (and conceivable the world) that
            operates websites collecting personally identifiable information
            from California consumers to post a conspicuous privacy policy on
            its website stating exactly the information being collected and
            those individuals with whom it is being shared, and to comply with
            this policy. – See more at:
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </div>
          <div>According to CalOPPA we agree to the following:</div>
          <div>users can visit our site anonymously;</div>
          <div>
            our Privacy Policy link includes the word “Privacy”, and can easily
            be found on the page specified above on the home page of our
            website;
          </div>
          <div>
            users will be notified of any privacy policy changes on our Privacy
            Policy Page;
          </div>
          <div>
            users are able to change their personal information by emailing us
            at help@linen.dev.
          </div>
          <div>Our Policy on “Do Not Track” Signals:</div>
          <div>
            We honor Do Not Track signals and do not track, plant cookies, or
            use advertising when a Do Not Track browser mechanism is in place.
            Do Not Track is a preference you can set in your web browser to
            inform websites that you do not want to be tracked.
          </div>
          <div>
            You can enable or disable Do Not Track by visiting the Preferences
            or Settings page of your web browser.
          </div>
          <div>
            Your Data Protection Rights under the California Consumer Privacy
            Act (CCPA)
          </div>
          <div>
            If you are a California resident, you are entitled to learn what
            data we collect about you, ask to delete your data and not to sell
            (share) it. To exercise your data protection rights, you can make
            certain requests and ask us:
          </div>
          <div>
            What personal information we have about you. If you make this
            request, we will return to you:
          </div>
          <div>
            The categories of personal information we have collected about you.
          </div>
          <div>
            The categories of sources from which we collect your personal
            information.
          </div>
          <div>
            The business or commercial purpose for collecting or selling your
            personal information.
          </div>
          <div>
            The categories of third parties with whom we share personal
            information.
          </div>
          <div>
            The specific pieces of personal information we have collected about
            you.
          </div>
          <div>
            A list of categories of personal information that we have sold,
            along with the category of any other company we sold it to. If we
            have not sold your personal information, we will inform you of that
            fact.
          </div>
          <div>
            A list of categories of personal information that we have disclosed
            for a business purpose, along with the category of any other company
            we shared it with.
          </div>
          <div>
            Please note, you are entitled to ask us to provide you with this
            information up to two times in a rolling twelve-month period. When
            you make this request, the information provided may be limited to
            the personal information we collected about you in the previous 12
            months.
          </div>
          <div>
            To delete your personal information. If you make this request, we
            will delete the personal information we hold about you as of the
            date of your request from our records and direct any service
            providers to do the same. In some cases, deletion may be
            accomplished through de-identification of the information. If you
            choose to delete your personal information, you may not be able to
            use certain functions that require your personal information to
            operate.
          </div>
          <div>
            To stop selling your personal information. We don&apos;t sell or
            rent your personal information to any third parties for any purpose.
            You are the only owner of your Personal Data and can request
            disclosure or deletion at any time.
          </div>
          <div>
            Please note, if you ask us to delete or stop selling your data, it
            may impact your experience with us, and you may not be able to
            participate in certain programs or membership services which require
            the usage of your personal information to function. But in no
            circumstances, we will discriminate against you for exercising your
            rights.
          </div>
          <div>
            To exercise your California data protection rights described above,
            please send your request(s) by one of the following means:
          </div>
          <div>By email: help@linen.dev</div>
          <div>
            Your data protection rights, described above, are covered by the
            CCPA, short for the California Consumer Privacy Act. To find out
            more, visit the official California Legislative Information website.
            The CCPA took effect on 01/01/2020.
          </div>
          <div>Service Providers</div>
          <div>
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), provide Service on our behalf,
            perform Service-related services or assist us in analysing how our
            Service is used.
          </div>
          <div>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </div>
          <div>Customer.io - email campaign service provider</div>
          <div>
            For more information on the privacy practices of Customer.io, please
            visit the Customer.io Privacy Terms web page:
            https://customer.io/legal/privacy-policy/
          </div>
          <div>Analytics</div>
          <div>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </div>
          <div>
            Google Analytics Google Analytics is a web analytics service offered
            by Google that tracks and reports website traffic. Google uses the
            data collected to track and monitor the use of our Service. This
            data is shared with other Google services. Google may use the
            collected data to contextualise and personalise the ads of its own
            advertising network.
          </div>
          <div>
            For more information on the privacy practices of Google, please
            visit the Google Privacy Terms web page:
            https://policies.google.com/privacy?hl=en
          </div>
          <div>
            We also encourage you to review the Google&apos;s policy for
            safeguarding your data:
            https://support.google.com/analytics/answer/6004245.
          </div>
          <div>
            PostHog PostHog is a product analytics platform built for the modern
            enterprise, with the differentiators of being open source and having
            a broader view of the tools needed to make a product successful.
          </div>
          <div>
            For more information about PostHog, please visit their Privacy
            Policy: https://posthog.com/privacy
          </div>
          <div>CI/CD tools</div>
          <div>
            We may use third-party Service Providers to automate the development
            process of our Service.
          </div>
          <div>GitHub</div>
          <div>GitHub is provided by GitHub, Inc.</div>
          <div>
            GitHub is a development platform to host and review code, manage
            projects, and build software.
          </div>
          <div>
            For more information on what data GitHub collects for what purpose
            and how the protection of the data is ensured, please visit GitHub
            Privacy Policy page:
            https://help.github.com/en/articles/github-privacy-statement.
          </div>
          <div>Payments</div>
          <div>
            We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g.
            payment processors).
          </div>
          <div>
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processors whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
          </div>
          <div>The payment processors we work with are:</div>
          <div>
            Stripe: Their Privacy Policy can be viewed at:
            https://stripe.com/us/privacy
          </div>
          <div>Links to Other Sites</div>
          <div>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party&apos;s site. We strongly advise you to review the
            Privacy Policy of every site you visit.
          </div>
          <div>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </div>
          <div>Children&apos;s Privacy</div>
          <div>
            Our Services are not intended for use by children under the age of
            18 (“Child” or “Children”).
          </div>
          <div>
            We do not knowingly collect personally identifiable information from
            Children under 18. If you become aware that a Child has provided us
            with Personal Data, please contact us. If we become aware that we
            have collected Personal Data from Children without verification of
            parental consent, we take steps to remove that information from our
            servers.
          </div>
          <div>Changes to This Privacy Policy</div>
          <div>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </div>
          <div>
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update
            “effective date” at the top of this Privacy Policy.
          </div>
          <div>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </div>
          <div>Contact Us</div>
          <div>
            If you have any questions about this Privacy Policy, please contact
            us:
          </div>
          <div>By email: help@linen.dev.</div>
          <div>By visiting this page on our website: linen.dev.</div>
        </div>
      </div>
    </div>
  );
}
