export default {
  thumbsup: '👍',
  '+1': '👍',
  thumbsdown: '👎',
  '-1': '👎',
  rock: '🪨',
  smiling_face_with_tear: '🥲',
  smiling_face_with_3_hearts: '🥰',
  shame: '😳',
  white_heavy_check_mark: '✅',
  done: '✅',
  pants: '👖',
  squirrel: '🐿️',
  // it would be nice to support gif, jpg, png and svg emojis
  partyparrot: '🦜',
  charmander: '🔥',
  java: '☕',
  slack: 'S',
  discord: 'D',
  github: 'G',
  jira: 'J',
  // we should either support custom emojis per community or hide them
  'airbyte-100': '💯',
  'airbyte-fire': '🔥',
  meow_party: '🎉',
  'octavia-hmm': '🤔',
  'octavia-hello': '👋',
};
