name: Testing

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'dev/**'
      - '**.md'

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: linentest
          POSTGRES_USER: linentest
          POSTGRES_DB: linentest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn migrate:test:db
      - run: yarn test:all
        env: 
          DATABASE_URL: "postgresql://linentest:linentest@localhost:5432/linentest"